import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                // Modern Professional Presence palette
                "surface": "#f7f9fb",
                "surface-dim": "#d8dadc",
                "surface-bright": "#f7f9fb",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f2f4f6",
                "surface-container": "#eceef0",
                "surface-container-high": "#e6e8ea",
                "surface-container-highest": "#e0e3e5",
                "on-surface": "#191c1e",
                "on-surface-variant": "#44474e",
                "inverse-surface": "#2d3133",
                "inverse-on-surface": "#eff1f3",
                "outline": "#75777f",
                "outline-variant": "#c5c6cf",
                "surface-tint": "#4b5e86",
                "surface-variant": "#e0e3e5",
                "primary": "#001231",
                "on-primary": "#ffffff",
                "primary-container": "#11274c",
                "on-primary-container": "#7b8fba",
                "inverse-primary": "#b3c6f4",
                "secondary": "#2e5f9f",
                "on-secondary": "#ffffff",
                "secondary-container": "#8bb8fd",
                "on-secondary-container": "#0a4786",
                "tertiary": "#001429",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#00294b",
                "on-tertiary-container": "#4c92db",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "primary-fixed": "#d8e2ff",
                "primary-fixed-dim": "#b3c6f4",
                "on-primary-fixed": "#021a3f",
                "on-primary-fixed-variant": "#33466d",
                "secondary-fixed": "#d5e3ff",
                "secondary-fixed-dim": "#a7c8ff",
                "on-secondary-fixed": "#001b3b",
                "on-secondary-fixed-variant": "#094785",
                "tertiary-fixed": "#d2e4ff",
                "tertiary-fixed-dim": "#9fcaff",
                "on-tertiary-fixed": "#001d36",
                "on-tertiary-fixed-variant": "#00497e",
                "background": "#f7f9fb",
                "on-background": "#191c1e",
                "deep-navy": "#11274C",
                "royal-blue": "#205493",
                "sky-accent": "#4B92DB",
                "ice-blue": "#D1E8FF",
                "success-emerald": "#059669",
                "warning-amber": "#D97706",
                "error-crimson": "#DC2626",
            },
            fontSize: {
                "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
                "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
            },
            spacing: {
                "stack-sm": "0.5rem",
                "stack-md": "1rem",
                "stack-lg": "2rem",
                "gutter": "1.5rem",
                "container-max": "1280px",
                "margin-mobile": "1rem",
                "margin-desktop": "2rem",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
            },
        },
    },

    plugins: [forms],
};
